#
# Copyright (c) 2019 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# CONFIG_NCS_SAMPLES_DEFAULTS=y
# CONFIG_DK_LIBRARY=y

#------ CPP -----
CONFIG_CPP=y


CONFIG_GPIO=y

# keep heap pool size
CONFIG_HEAP_MEM_POOL_SIZE=8192

#------ ESB -----
CONFIG_ESB=y
CONFIG_ESB_MAX_PAYLOAD_LENGTH=252
CONFIG_CLOCK_CONTROL=y
CONFIG_NRFX_DPPI10=y

#------ UART -----
# use ASYNC uart API
CONFIG_SERIAL=y
CONFIG_UART_ASYNC_API=y
# CONFIG_NET_BUF=y
CONFIG_UART_NRFX_UARTE_ENHANCED_RX=y
CONFIG_NRF_SYS_EVENT=y

#------ logging AND console ----
CONFIG_LOG=n
# CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_NEWLIB_LIBC=n
CONFIG_LOG_BACKEND_UART=n
CONFIG_LOG_BACKEND_RTT=n
# CONFIG_STACK_SENTINEL=y
# CONFIG_THREAD_STACK_INFO=y
# CONFIG_ASSERT=y

# choose console
CONFIG_USE_SEGGER_RTT=n
CONFIG_RTT_CONSOLE=n
CONFIG_UART_CONSOLE=n

#------ sensors ----
CONFIG_ADC=y
CONFIG_I2C=y
# CONFIG_SENSOR=y

#------ BLE -----
# CONFIG_BT=y
# CONFIG_BT_PERIPHERAL=y
# CONFIG_BT_DEVICE_NAME="Nordic_UART_Service"
# CONFIG_BT_MAX_CONN=1
# CONFIG_BT_MAX_PAIRED=1
# CONFIG_BT_NUS=y
# CONFIG_BT_BUF_ACL_RX_SIZE=251
# CONFIG_BT_BUF_ACL_TX_SIZE=251
# CONFIG_BT_L2CAP_TX_MTU=247