#
# Copyright (c) 2019 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

#------ APP node ID ----
# EXO_NODE_ESB_FOOT_RIGHT
CONFIG_EXO_NODE_ID=3

#------ logging AND console ----
CONFIG_NCS_BOOT_BANNER=n
CONFIG_BOOT_BANNER=n
CONFIG_LOG=n
CONFIG_CONSOLE=n
CONFIG_PRINTK=n
CONFIG_USE_SEGGER_RTT=n
CONFIG_RTT_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_LOG_BACKEND_RTT=n

#------ DEBUG ----
# CONFIG_STACK_SENTINEL=y
# CONFIG_THREAD_STACK_INFO=y
# CONFIG_INIT_STACKS=y
# CONFIG_ASSERT=y

#------ OPTIMIZATIONS -----
CONFIG_DEBUG_OPTIMIZATIONS=y

#------ CPP -----
CONFIG_CPP=y

#------ FPU -----
CONFIG_FPU=y
CONFIG_NEWLIB_LIBC=y

#------ HEAP -----
CONFIG_HEAP_MEM_POOL_SIZE=8192

#------ GPIO -----
CONFIG_GPIO=y

#------ UART -----
CONFIG_SERIAL=n

#------ Sensors -----
CONFIG_I2C=y
CONFIG_SPI=y
CONFIG_ADC=y
CONFIG_SENSOR=n

#------ ESB (PTX) -----
CONFIG_ESB=y
CONFIG_ESB_MAX_PAYLOAD_LENGTH=252
CONFIG_CLOCK_CONTROL=y

# No BLE
